language: c 
sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker build -t standalone-dell-recovery -f docker/Dockerfile-debian-slim .

script:
  - docker run -t -v `pwd`:/build standalone-dell-recovery ./docker/build_and_test.sh

deploy:
  provider: releases
  api_key:
    secure: fcaad59a0dc82202ff7107d86a35fd42670740d3
  file_glob: true
  file: build/out/dell-recovery-standalone.iso
  skip_cleanup: true
  on:
    tags: true
