FROM debian:stable-slim
RUN apt-get update -qq
RUN DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
        dosfstools \
        grub-common \
	ca-certificates \
	dmidecode \
	efibootmgr \
	dbus-x11 \
	fluxbox \
	nodm \
	gir1.2-udisks-2.0 \
	gir1.2-gtk-3.0 \
	git \
	gnu-efi \
	linux-image-amd64 \
	live-boot \
	live-config \
	live-config-systemd \
	live-boot-initramfs-tools \
	lsb-release \
	plymouth-themes \
	python3-apt \
	python3-debian \
	python3-dbus \
	python3-distutils-extra \
	python3-gi \
	python3-git \
	squashfs-tools \
	systemd \
	systemd-sysv \
	udisks2 \
	uuid-runtime \
	xterm \
	xserver-xorg-video-fbdev \
	xserver-xorg-input-all \
	xfonts-100dpi \
	xfonts-75dpi \
	xorriso	\
	xz-utils
RUN apt-get update -qq
RUN mkdir /build
WORKDIR /build
